# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

matrix:
  fast_finish: true
  allow_failures:
    - env: WP_VERSION=3.8 WP_MULTISITE=0
      php: nightly
    - env: WP_VERSION=3.8 WP_MULTISITE=1
      php: nightly

# Grab the setup script and execute
before_script: # Make PHP 7 test work. https://github.com/WebDevStudios/CMB2/pull/885
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
     composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - phpunit --version

script: phpunit

# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup
